"""add_intelligence_features

Revision ID: 2e6f3c8958da
Revises: e43db2d0d9e8
Create Date: 2026-01-21 18:18:35.391585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e6f3c8958da'
down_revision: Union[str, None] = 'e43db2d0d9e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('narrative_clusters', sa.Column('structured_summary', sa.JSON(), nullable=True))
    op.add_column('narrative_clusters', sa.Column('velocity', sa.Float(), nullable=True))
    op.add_column('narrative_clusters', sa.Column('emergence_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('narrative_clusters', 'emergence_score')
    op.drop_column('narrative_clusters', 'velocity')
    op.drop_column('narrative_clusters', 'structured_summary')
    # ### end Alembic commands ###
