"""add_patient_zero_real

Revision ID: e43db2d0d9e8
Revises: d67c83593e02
Create Date: 2026-01-21 18:02:06.956975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e43db2d0d9e8'
down_revision: Union[str, None] = 'd67c83593e02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('narrative_clusters', sa.Column('first_message_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('narrative_clusters', sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('narrative_clusters', sa.Column('primary_source_channel_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'narrative_clusters', 'channels', ['primary_source_channel_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'narrative_clusters', type_='foreignkey')
    op.drop_column('narrative_clusters', 'primary_source_channel_id')
    op.drop_column('narrative_clusters', 'last_message_at')
    op.drop_column('narrative_clusters', 'first_message_at')
    # ### end Alembic commands ###
